### ISSUE TITLE
No executable

### ISSUE THREAD

**Issue by efeakaroz13** [hnlq715/jumpcutter#1]
Hello, I liked your software and i wanted to install it on my computer but I was getting an error while installing OpenCV on mac, I installed it on windows I had all modules installed ffmpeg and opencv too. When I tried to run it there was a problem with FFmpeg it says "a.mp4 not such file or directory" it was in the folder of source code I put it there. Then i pasted the whole folder path to --input-file but it didn’t help and gave the same error. Can you make an executable(command line or GUI it doesn’t matter)? I liked your idea and code but right now i am stuck.

**Comment by sysulq** [comment]
@efeakaroz13 Thanks.
I found a better implementation from https://github.com/WyattBlue/auto-editor, which saved me a lot time, hope you enjoy it :-)
